version: '3.8'

services:
  frontend:
    image: serhatsdocker/fe:project
    ports:
      - "3000:80"

  backend:
    image: serhatsdocker/be:project
    ports:
      - "5000:80"

  database:
    image: serhatsdocker/db:project
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=todo_app
      - MYSQL_USER=todo_admin
      - MYSQL_PASSWORD=password
